/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ltm;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import model.User;
import model.sendObject;

/**
 *
 * @author huuan
 */
public class bxh extends javax.swing.JFrame {

    /**
     * Creates new form bxh
     */
    ArrayList<User> list;
    static User user;
    ObjectOutputStream oos;
    Socket socket;
    ObjectInputStream ois;

    public bxh(User user1) throws IOException, ClassNotFoundException {
        initComponents();
        setLayout(null);
        setSize(700, 450);
        ImageIcon background_login = new ImageIcon("background-login.png");
        JLabel back = new JLabel("", background_login, JLabel.CENTER);
        back.setBounds(-300, -220, 1200, 700);
        add(back);
        socket = new Socket("localhost", 1999);
        oos = new ObjectOutputStream(socket.getOutputStream());
        ois = new ObjectInputStream(socket.getInputStream());
        user = user1;
        sendObject object1 = new sendObject(user, "bxh");
        oos.writeObject(object1);
        list = (ArrayList<User>) ois.readObject();
        System.out.println("Receive point win");
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        for (int i = 0; i < list.size(); i++) {
            String data[] = {list.get(i).getUserName(), String.valueOf(list.get(i).getPoint()),
                String.valueOf(list.get(i).getWin())};
            model.addRow(data);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        point = new javax.swing.JButton();
        win = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Người chơi", "Điểm", "Số trận thắng"
            }
        ));
        jScrollPane1.setViewportView(table);

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BẢNG XẾP HẠNG");

        point.setText("ĐIỂM");
        point.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointActionPerformed(evt);
            }
        });

        win.setText("SỐ TRẬN THẮNG");
        win.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                winActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(back)
                        .addGap(62, 62, 62)
                        .addComponent(point)
                        .addGap(59, 59, 59)
                        .addComponent(win)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(point)
                    .addComponent(win))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.dispose();
        login.table.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void pointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointActionPerformed
        try {
            // TODO add your handling code here:
            sendObject object = new sendObject(user, "point");
            oos.writeObject(object);
            System.out.println("Receive point");
            list = (ArrayList<User>) ois.readObject();
            for (int i = 0; i < list.size(); i++) {
                System.out.println(list.get(i).getUserName());
            }
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setRowCount(0);
            for (int i = 0; i < list.size(); i++) {
                String data[] = {list.get(i).getUserName(), String.valueOf(list.get(i).getPoint()),
                    String.valueOf(list.get(i).getWin())};
                model.addRow(data);
            }
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(bxh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pointActionPerformed

    private void winActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_winActionPerformed
        try {
            // TODO add your handling code here:
            sendObject object = new sendObject(user, "win");
            oos.writeObject(object);
            System.out.println("Receive win");
            list = (ArrayList<User>) ois.readObject();
            for (int i = 0; i < list.size(); i++) {
                System.out.println(list.get(i).getUserName());
            }
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setRowCount(0);
            for (int i = 0; i < list.size(); i++) {
                String data[] = {list.get(i).getUserName(), String.valueOf(list.get(i).getPoint()),
                    String.valueOf(list.get(i).getWin())};
                model.addRow(data);
            }
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(bxh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_winActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bxh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bxh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bxh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bxh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new bxh(user).setVisible(true);
                } catch (IOException | ClassNotFoundException ex) {
                    Logger.getLogger(bxh.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton point;
    private javax.swing.JTable table;
    private javax.swing.JButton win;
    // End of variables declaration//GEN-END:variables
}
